version: '3'

networks:
  laravel:

services:

  web:
    image: nginx
    container_name: voca_web
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./default-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voca_php
    volumes:
      - .:/var/www/html
    ports:
      - 9000:9000
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: voca_mailhog
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      - laravel

  db:
    image: postgres
    container_name: voca_db
    restart: unless-stopped
    tty: true
    ports:
      - 3307:5432
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: voca
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    networks:
      - laravel
